volumes:
  taski_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - taski_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      db:
        condition: service_healthy

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80
    depends_on:
      - backend
